#!/usr/bin/env bash

## Description: Launch a browser with Mongo Express
## Usage: mongo-express
## Example: "ddev mongo-express"

# Define ANSI Color Codes
GREEN='\033[0;32m' # Green
RED='\033[0;31m'   # Red
NC='\033[0m'      # No Color / Reset

# Determine whether to use HTTP or HTTPS based on environment
PROTOCOL="HTTP"
if [ "${DDEV_PRIMARY_URL%://*}" != "http" ] && [ -z "${GITPOD_WORKSPACE_ID:-}" ] && [ "${CODESPACES:-}" != "true" ]; then
    PROTOCOL="HTTPS"
fi

# Start mongo-express if it's not started
ddev exec -s mongo-express true >/dev/null 2>&1 || ddev start --profiles mongo-express

# Fetch the appropriate port within the mongo-express container
DDEV_MONGO_EXPRESS_PORT=$(ddev exec -s mongo-express sh -c "printenv | grep -w ${PROTOCOL}_EXPOSE | cut -d '=' -f 2 | cut -d ':' -f 1")

if [ -z "$DDEV_MONGO_EXPRESS_PORT" ]; then
    printf "${RED}Error: Could not retrieve Mongo Express port.${NC}\n"
    exit 1
fi

# Echo the colored link using printf for cross-shell compatibility
printf "${GREEN}Mongo Express is ready at: ${DDEV_PRIMARY_URL}:${DDEV_MONGO_EXPRESS_PORT}${NC}\n"
