#!/usr/bin/env bash

## Description: Wait 10 seconds then start mongo-express
## Usage: mongo-wait
## Example: "ddev mongo-wait"

: <<'BATCH'
@echo off
timeout /t 10 > nul
ddev mongo-express
exit /b
BATCH

# Linux section
sleep 10
ddev mongo-express
